### ISSUE TITLE
Auto loading default config file

### ISSUE THREAD

**Issue by okuryu** [yahoo/atomizer#140]
I'm new to Atomic CSS right now, so I have a suggestion for future feature on Atomizer tools.

I realized that perhaps we should be reading any config file (e.g.: `Atomicfile.js`) as default. You know it's similar behavior with Grunt, gulp, and Broccoli. Thought?

**Comment by renatoi** [comment]
We could do it but we would have to enforce the location and the name of the config file. This could be a good idea, but right now you have the flexibility to add it to any location and give it any name. You could, in theory, enforce standards within your org to always name it Atomicfile.js at the root level.
