### ISSUE TITLE
Atomizer should be able to chain pseudo-classes

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#145]
A valid use case is when we want the same styling for `:hover` and `:focus` (for links for example).
Users should be able to do something like `Td-u:h:f` to get text decoration on mouseover **and** focus.

I think it is better than having to repeat the class with a different pseudo-class (`Td-u:h Td-u:f`) &mdash; that seems very noisy to me.

**Comment by renatoi** [comment]
As discussed, I'm closing this issue since chaining makes the class not reusable.
