### ISSUE TITLE
Name for border-left-width

### ISSUE THREAD

**Issue by hankhsiao** [yahoo/atomizer#154]
Is it ``Bdstartw`` instead of ``Bdsw``, @renatoi?

**Comment by hankhsiao** [comment]
https://github.com/yahoo/atomizer/blob/master/src/rules.js#L451

**Comment by thierryk** [comment]
[PR #157](https://github.com/yahoo/atomizer/pull/157) fixes this.

(Thanks Hank for spotting this)
