### ISSUE TITLE
getting 'can not process border-bottom of null' error

### ISSUE THREAD

**Issue by 6zz** [yahoo/atomizer#177]
I have atomizer@3.0.0-alpha.5 (latest) and grunt-atomizer@3.0.0-alpha.4 (latest) when I got the error.  Downgraded to atomizer@3.0.0-alpha.1 and grunt-atomizer@3.0.0-alpha.1 the error went away.
<snip> ping me for the source that shows this issue.

**Comment by src-code** [comment]
Apparently this was resolved sometime around 3.0.0-alpha.6
