### ISSUE TITLE
Please add Fz(xs) Fz(s)  Fz(n) Fz(l)  Fz(xl)  

### ISSUE THREAD

**Issue by 3den** [yahoo/atomizer#188]
@thierryk @renatoi It would be very nice to have some defaults for font-size can we add those to atomizer?

**Comment by thierryk** [comment]
@3den what do you mean? Could you give us a couple of examples?

**Comment by 3den** [comment]
I mean some default values for font sizes so we abstract a little (like what stencil does).

**Comment by thierryk** [comment]
@3den please see https://github.com/yahoo/atomizer/pull/189#issuecomment-98379576

What about a PR to add custom rules for this in the [config example](https://github.com/yahoo/atomizer/blob/master/examples/example-config.js)? ;)
