### ISSUE TITLE
Web app for Atomizer

### ISSUE THREAD

**Issue by pankajparashar** [yahoo/atomizer#192]
I think it would be interesting if there is an online app that takes in the markup of an HTML document and spits out an `atomic.css` file containing the relevant CSS rulesets.

Needless to say that I have already started working on the web app that uses browserify to bundle up the npm module for `atomizer` for it to be useable with plain-old JavaScript.

Would love to hear your thoughts on the possible approaches for building this.

**Comment by renatoi** [comment]
It is definitely possible and in our radar. The atomizer.js file we have has the method [findClassNames()](https://github.com/yahoo/atomizer/blob/master/src/atomizer.js#L74) which will generate a config and then you can pass this config to [getCss()](https://github.com/yahoo/atomizer/blob/master/src/atomizer.js#L74) to get the CSS.

**Comment by pankajparashar** [comment]
I spent few hours over the weekend and dished out a quick little web app for atomizer that can be found here,

http://pankajparashar.com/atomizer-web/

Ofcourse it is far from complete but let me know what you guys think of it!

**Comment by renatoi** [comment]
Wow, sorry for the late response, but this is awesome man! Good job. I'll suggest adding to our docs if you don't mind.

**Comment by pankajparashar** [comment]
Thanks! Feel free to add it into the docs. Its still not perfect though but definitely a good start.

**Comment by thierryk** [comment]
Closing this as I submitted a [PR for acss.io](https://github.com/yahoo/acss-site/pull/103) 

Thanks again @pankajparashar for the awesome tool!
