### ISSUE TITLE
Provide docs on the shortened class names

### ISSUE THREAD

**Issue by corysimmons** [yahoo/atomizer#200]
I can't find where things like `C(#ff0)` and `P(10px)` are specified. Are these literally just taken straight from Emmet? If so, it'd be nice to provide a link to a list of these shorthand tags.

**Comment by redonkulus** [comment]
@corysimmons what about the reference page? http://acss.io/reference

**Comment by corysimmons** [comment]
Ah perfect. I'm an idiot. I was looking at the Docs pages and forgot to look at the Reference page.
