### ISSUE TITLE
Add SVG classes

### ISSUE THREAD

**Issue by 3den** [yahoo/atomizer#209]
To support SVG styles we need atomizer classes for:

* fill
* stroke
* stroke-width
* stroke-dasharray
* stroke-dashoffset

**Comment by src-code** [comment]
I think this is a good idea.  We'll want to use names in the rules that makes it clear that these are SVG related.

**Comment by 3den** [comment]
@src-code what you think about the syntax below?

```
fill = Fill()
stroke = Sk()
stroke-width = Skw()
stroke-dasharray = Skda()
stroke-dashoffset = Skdo()
```

**Comment by 3den** [comment]
if that is ok i can send a PR today

**Comment by src-code** [comment]
Emmet is silent on this one, so we're on our own for syntax.  `Sk*` is a little ambiguous I think, because we already have a bunch of `Skew*` classes for styling transforms, and these might be confused for those (eg, `Skw()`)  So maybe it'd be better to do something like `Stk` or `Strk`?

**Comment by 3den** [comment]
i like Stk

**Comment by src-code** [comment]
If there's no objections from @renatoi or @thierryk, I'd say let's go with `Stk` then.  I'd follow the example of the Transform classes in how you name the rules (eg, "Fill (SVG)")
