### ISSUE TITLE
Pseudo syntax isn't compatible with IE < 8

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#224]
In IE < 8, the colon char isn't valid in CSS selectors, even if escaped, it seems.  For instance, the class 
`box:h_D(n)!` will apply correctly in IE 8+, but will not apply in IE < 8.  The only way to get the class to apply is to modify it to remove the colon, from what I've found so far.

Simple test case here:
https://gist.github.com/src-code/4c17ecfbcac43e0ca12a

@dnewcome @thierryk @renatoi @3den

**Comment by src-code** [comment]
To be clear, other escaped chars such as `(` and `!` don't seem to cause problems - only colons.

**Comment by src-code** [comment]
So here's a few ideas on how to address this, assuming we can't find a way to make IE < 8 accept the colons:

1. Introduce a new char for pseudos, and deprecate `:`.  
2. Ignore it, and leave it up to developers to cope with archaic browseres by writing custom styles outside of Atomizer
3. ???

**Comment by redonkulus** [comment]
honestly, since this is for older browsers, I'd lean towards #2, instead of changing the API again.

**Comment by src-code** [comment]
@redonkulus I'm leaning that way too.  We could just document the issue as a known limitation of old-browser support.

**Comment by 3den** [comment]
I agree with, the api is fine as it is. RIP: IE 7

**Comment by dnewcome** [comment]
Agree not to change the API. Using a char different than what is standard in CSS will just make the Atomizer syntax more confusing for little benefit.

**Comment by src-code** [comment]
Ok, it seems we're all on the same page here.  We won't fix pseudos in IE < 8, and leave it up to developers to cope through custom styles.  I'll add a note to our docs for this.

**Comment by src-code** [comment]
https://github.com/yahoo/acss-site/pull/90
