### ISSUE TITLE
Quickstart FAQ link points to localhost:3000

### ISSUE THREAD

**Issue by bebraw** [yahoo/atomizer#225]
1. http://acss.io/quick-start.html
2. Search for "FAQ"
3. Hit it -> http://localhost:3000/frequently-asked-questions.html

Looks like that should be http://acss.io/frequently-asked-questions.html .

**Comment by redonkulus** [comment]
@bebraw the steps are for running it locally on your computer. acss.io wouldn't work in that case, thats why localhost is specified.

**Comment by src-code** [comment]
Thanks @bebraw, I'll fix that one!

**Comment by redonkulus** [comment]
I see now, the link you are referring to is that the bottom.

**Comment by src-code** [comment]
Fixed!  Deploying shortly...
