### ISSUE TITLE
Webpack integration?

### ISSUE THREAD

**Issue by bebraw** [yahoo/atomizer#226]
Are there plans for some sort of webpack integration?

**Comment by redonkulus** [comment]
@bebraw what type of webpack integration are you envisioning?

**Comment by bebraw** [comment]
@redonkulus I expect it would have to work through a loader at least. That would allow you to match against files to parse the rules from and then to emit them to webpack. You'll likely have to study some of the existing loaders to get an exact idea of how to achieve this.

I asked about possible integration as I would love to cover Atomic CSS at my [styling chapter](http://survivejs.com/webpack_react/styling_react/).

**Comment by renatoi** [comment]
@bebraw Check https://github.com/tom76kimo/atomic-loader

**Comment by bebraw** [comment]
@renatoi Thanks for linking!
