### ISSUE TITLE
Add rule for "content"

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#237]
Atomizer doesn't currently offer a style rule for `content`, which would be useful especially when paired with pseudo element support (issue #236)

**Comment by src-code** [comment]
Following Emmet, the matcher would be `Cnt` I believe

**Comment by gbor** [comment]
+1 and :+1: for this

**Comment by src-code** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/content

**Comment by src-code** [comment]
Note: Atomizer will support a single param-to-value, though `content` allows for multiple values to be passed.

Also, Atomizer normally uses the shorthand `n` for either `none` or `normal`, but in this case both are valid values.  So I'll go with `n` for `none` and `nor` for normal...
