### ISSUE TITLE
+ and ~ (sibling operators) don't match docs, or don't work

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#240]
According to the syntax docs (http://acss.io/guides/syntax.html), you can provide an adjacent or general sibling combinator (+ or ~ respectively) to target sibling nodes.  In reality, `+` acts like a "reverse sibling" operator (and thus doesn't work as the docs describe) and `~` doesn't seem to be recognized.  For example, the following input to Atomizer v3.2.0:

```
foo+D(n)
```
Produces the following output:

```
.foo + .foo\+D\(n\) {
  display: none;
}
```

While technically valid CSS, it's not correct if your goal is to style the adjacent sibling of the node on which you placed the Atomic class, which is what the documentation describes.  Instead, the `.foo` node and the node with the Atomic class need to be siblings, and you're really just saying "only apply this style if I'm preceded by `.foo`".  You can't really style your node's next sibling with this.  So either the docs are wrong in multiple ways, or the CSS output is wrong.  FWIW, [the grammar JS considers `+` as a *parent* selector in the regex](https://github.com/yahoo/atomizer/blob/master/src/lib/grammar.js#L53), which is wrong. 

For the example in our docs to work, I believe it should be written as `foo_D(n)+div` or maybe `foo_D(n)+*`.  This would require changes to our grammar parsing, of course.  But I suspect that the intent here was to say "only apply this class if my previous sibling was `.foo`.

So the question is, which syntax did we mean to support here?  

As for `~`, that doesn't work at all:

 ```
foo~D(n)
```
Produces no CSS.  I don't see mention of `~` in the grammar regex at all, in fact.

fyi @renatoi @dnewcome @3den @thierryk

**Comment by renatoi** [comment]
`~` was never implemented but it was documented.

In regards to `+`, I believe the intent, as you said, was to only apply styles if the class is preceded by the given class. I might be wrong, but I believe this is being used somewhere by td-app-yahoo and I'd check the use case there first.

@thierryk might be able to answer that better.

**Comment by src-code** [comment]
Thanks @renatoi.  I'm debating whether I should enhance this so that you can provide a sibling selector at the end of a classname, eg:

`foo_D(n)!:h--small+next_sibling_class`
`foo_D(n)!:h--small~next_siblings_class`

The problem would be, this is unlike other Atomic classes in the sense that it'd be styling elements that don't have Atomic classes on them.  That makes me uncomfortable.  On the other hand, it does allow one to combine parent selectors and sibling selectors in a single class, which today isn't possible.  And I can't see a way to support `~` without this change.

That said, leaving it as is is more consistent with the descendent selectors - i.e., only apply the style to the current element if its in relation to another element.  

So either we leave it as is, and fix the documentation (and remove docs for `~`, which will never be supported), or we add support for having `+` and `~` as suffix selectors, which opens up new possibilities but might go against the way Atomic is expected to work.

The more I type, the more I find myself leaning toward leaving things as is and fixing the docs.  But I'd be interested to hear your thoughts on adding the suffix style as well (I'm already well along in prototyping this - the grammar JS makes it quite easy! ;) )

**Comment by thierryk** [comment]
The docs say:

> Use the adjacent sibling combinator to style the element only if its the sibling of a specified element
> 
> Example:
>
> `<div class="foo"></div>`
> `<div class="foo+D(n)"></div>`
>
> This class hides the element if its previous sibling has the class foo attached to it.

@src-code says:

> ` foo+D(n)`
>
> Produces the following output:
>
>`.foo + .foo\+D\(n\) {`
>`  display: none;`
>`}`

It looks like the example in the docs + the CSS output work as described in the docs: http://jsfiddle.net/cdbzg78h/
Also, if I recall, and as @renatoi suggested, I believe we used this on td-app-yahoo.

Or am I missing something?

PS: sorry guys for the delay but I was in Mexico with no laptop :)

**Comment by src-code** [comment]
@thierryk Sorry, I updated the docs already! :)  And it wasn't in use internally as far as I could find, though it could've been (and now will be)

**Comment by thierryk** [comment]
@src-code it's me who's sorry for not checking the diff before commenting ;)

> While technically valid CSS, it's not correct if your goal is to style the adjacent sibling of the node on which you placed the Atomic class, which is what the documentation describes.

You're correct, the documentation as it was written relied on something like you suggested:

```css
.next\+D\(n\) + * {
  display: none;
}
```

Making `foo` irrelevant.

```html
<div class="foo">
    <div class="next+D(n)">zero</div>
    <div class="one">one</div>
    <div class="two">two</div>
    <div class="three">three</div>
</div>
```

I'm not sure what's best: sibling or "reverse sibling" (as you call it)? 
The original intent was to style a node according to a class on its previous sibling and I believe we used this on td-app-yahoo to manage sub-navigation menus on mobile (or something like that).

May be we could add the *next* syntax (as I wrote above)?

Thoughts?

**Comment by src-code** [comment]
@thierryk Yeah, I've come to the conclusion that leaving the existing behavior (styling current node based on context) is the way to leave it, and then we can explore adding further syntax in the future.  Though I'm increasingly wary of styling nodes that don't have Atomic classes on them (as ` + *` would do), so maybe it's not something worth pursuing until we have a really good reason to.

Closing this one out now that the docs are updated, thanks guys!
