### ISSUE TITLE
"start" instead of "left", "end" instead of "right"... seriously guys.

### ISSUE THREAD

**Issue by andresn** [yahoo/atomizer#247]

**Comment by koulmomo** [comment]
I'm pretty sure atomizer uses `start` and `end` since `left` and `right`don't make sense when supporting `rtl` (ie: in `rtl` a `margin-right` would actually add a `left margin`, whereas adding a margin at the **end** can mean either depending on the context you are in) 

right @thierryk ?

**Comment by andresn** [comment]
Yeah that makes sense, I got myopic deving for a US only intl for a while now. One thing though, can you add that note next to a Margin Left header in your reference section? E.g:

Margin Left
Use Margin Start Instead (this allows Atomic to support web pages written right to left for you automatically)

**Comment by src-code** [comment]
@koulmomo @andresn Correct about RTL.  And I agree, it could be documented better.  We have it mentioned in a couple of spots, but it could certainly be made more clear:

http://acss.io/guides/syntax.html#rtl-ltr
http://acss.io/frequently-asked-questions.html#how-can-one-remember-atomic-class-names-

**Comment by koulmomo** [comment]
fyi Android has adopted the same naming convention for RTL support as of [API 4.2](https://developer.android.com/about/versions/android-4.2.html#RTL) so the "start" "end" convention should get more popular over time.

**Comment by whmountains** [comment]
Yes, I totally agree that the current convention is correct, but it could be documented better.  I'm learning ACSS and it was really frustrating to find no results in the acss reference for `margin-right`.

**Comment by src-code** [comment]
@whmountains That's a good observation - It certainly seems like we could fix search pretty easily, perhaps by having an additional "searchable name" in the ruleset for such cases.  Then you could search for "start" or "right" and still get the same results...

**Comment by whmountains** [comment]
Yes, that would be soo nice!

**Comment by thierryk** [comment]
As a side note, you could check in Chrome inspector that the user-agent style sheet already contains things like `-webkit-padding-start`, etc.

**Comment by thierryk** [comment]
@src-code shouldn't close this now?

**Comment by src-code** [comment]
@thierryk We'll just want to track the idea of making it easier to search for right/start left/end in the docs... I'll open an issue over on the acss-site repo.
