### ISSUE TITLE
Gulp plugin

### ISSUE THREAD

**Issue by whmountains** [yahoo/atomizer#252]
Hi guys, I made a gulp plugin for Atomizer.  I'm an amateurish dev and so there may be some issues with it but I've tried to follow all the gulp guidelines as best as possible.  It's unit tested and working fine in my current project.

Would you consider adding it to the list of integrations in the Readme?

EDIT: whoops, my repo is at: https://github.com/whmountains/gulp-atomizer

**Comment by src-code** [comment]
@whmountains That's great to see, thank you!  I'll try it out today and we'll add it to the list of integrations!
