### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nueverest** [yahoo/atomizer#259]
Consider an integration option that auto-generates the javascript based virtual stylesheets of the form used in PowerCSS [https://github.com/mmikowski/powercss](https://github.com/mmikowski/powercss).  

This would allow for CSS to be compiled in Real-Time.

**Comment by thierryk** [comment]
@nueverest could you please be more specific? I watched the video and it does not say how styles are *created*, and the example page does not explain much either. All these do is showing style sheets swapping&mdash;which is not new. It is not clear how the styling itself (the rules) is created.

Also, compiling CSS in real-time requires JS on the client (extra asset) and some unnecessary computation that can only hurt performance. Lastly, I don't think it is a good idea to rely 100% on JS for styling... Or am I missing something here?

**Comment by nueverest** [comment]
In PowerCSS the CSS is generated from a javascript file that contains a virtual stylesheet definition.  [https://github.com/mmikowski/powercss#3-add-virtual-stylesheets](https://github.com/mmikowski/powercss#3-add-virtual-stylesheets). If it was combined with the Atomizer no CSS file would be necessary (unless you want to have some non-atomic class selector definitions).  A single web page normally does not require that much CSS class selector compilation (generally we would be talking about milliseconds on the client).

Each HTML file has a JS file with a virtual stylesheet used to auto-generate CSS.  It is a novel concept, and I can understand the difficulty in immediately seeing the benefit.

The great benefit is flexibility.  The style on the page could morph as the user interacted with it.  In-browser HTML/CSS editors could become more powerful. There would also no longer be a need to download a CSS resources reducing the performance hit of the HTTP Request/Response cycle.

**Comment by thierryk** [comment]
> There would also no longer be a need to download a CSS resources reducing the performance hit of the HTTP Request/Response cycle.

What about the JS needed to build those styles sheets on the fly? What about the JSON files that contain the styles? I'm sorry but I have a hard time seeing the gain here. I looked at the [example page](http://powercss.org/) to see if it does make more sense in term of assets to download but I see that page loads more than 110Kb of JS (80Kb+ if we ignore JQuery). That's a lot of JS. Is there other pages we could check that demonstrate all the gain you're talking about? I'm sorry but I'm still not seeing the benefits...

For example, Atomizer writes only the styles needed for the page which would correspond more or less to the JSON file needed by PowerCSS to make things work, so why would we want to add JavaScript on the client to write that same style sheet on the fly? And failing to style the document if there was no script support...

**Comment by nueverest** [comment]
You make some good points about the JS asset downloads and the no script support case in particular.
