### ISSUE TITLE
Plugging info at the top of atomic.css file

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#48]
I think the config file could hold some "meta data" and output that at the top of atomic.css.
I'm thinking of author's name, project name, version(?), and stuff like that (time stamp too?)...

**Comment by 3den** [comment]
:+1: that would be cool

**Comment by src-code** [comment]
Right now we support this via the "banner" option.  You can pass any arbitrary text you want, and it'll be placed at the top of the CSS file.
