### ISSUE TITLE
Add CLI options for generating default config

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#66]
Right now the CLI tool requires you to pass a default config file, because at the very least we need the `config` preamble at the beginning of the config file (stuff like `namespace`, `start`, `end` are defined within `config`.)  We should allow those config params to be passed as args to the CLI so that users won't have to manually create a config file to get started.

**Comment by renatoi** [comment]
Maybe these should be optional as well, as we could have a default value for them.

```javascript
{
  namespace: '#atomic',
  start: 'left',
  end: 'right'
}
```

**Comment by src-code** [comment]
@renatoi Yeah, definitely!

**Comment by src-code** [comment]
`start`/`end` have been replaced by `rtl` option.  `namespace` is now also an option, but is not yet exposed via the CLI (issue #89)
