### ISSUE TITLE
Allowing "space" inside suffixes

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#88]
Here is a typical use case (for transition): `Trs-all_2s`

Atomizer would replace the `_` with a space:

```css
.Trs-all_2s {
    transition: all 2s;
}
``

**Comment by src-code** [comment]
I'm not personally a fan of using complex string-based values as suffixes like this... do we know this is a safe thing to do with all possible values that might appear as suffixes?  Not supporting string-based values would negate the need to deal with spaces...

**Comment by src-code** [comment]
This has been solved by the switch to the parenthesis syntax...
