### ISSUE TITLE
Helpers: Single-pixel border helpers

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#93]
From issue #76:

> For the record: helpers.css (from another repo) has been updated with border classes meant to help when styling boxes with a single pixel border but those rules need to integrate Atomizer somehow.

More details from @thierryk:

> border needs 3 values: `width style color`. We can get style borders the way we want with Atomizer by using those 3 but a common use case is to style border with  a single pixel, so what we added to the helper classes are border declarations mixing both `style` and `width`

> that way authors can do this: `Bd Bdc-000` to get a black border around a box instead of having to go verbose with Atomic `Bdc-000 Bds-s Bdw-1px`

**Comment by thierryk** [comment]
@src-code what is this issue about exactly? The helpers for single pixel border *are done already*. In my opinion, all we need now is to open an issue (if not done already) to integrate most rules in that `helpers.css` file into Atomizer.

**Comment by src-code** [comment]
@thierryk This issue was to track that specific item to be added to Atomizer.  If you'd rather, we could make the issue more generic for simply creating a helpers ruleset in Atomizer, and assume that these helpers would just be part of that.

**Comment by thierryk** [comment]
@src-code Yes, I think that would make more sense to track the fact that helpers need to be integrated into Atomizer as a whole. With `true`/`false` flags in case people don't want them or want to cherry pick those rules.

**Comment by src-code** [comment]
Ok, created issue #96 to track helpers more generically.
