### ISSUE TITLE
Add ruleset for helper classes

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#96]
We've been discussing the addition of a new ruleset for helper classes, which would allow developers to pick and choose which helpers they want to include in their CSS.  Let's use this issue to track the helpers we want to add.

@thierryk @renatoi

**Comment by src-code** [comment]
Border helpers.  From issue #76:

> For the record: helpers.css (from another repo) has been updated with border classes meant to help when styling boxes with a single pixel border but those rules need to integrate Atomizer somehow.

More details from @thierryk:

> border needs 3 values: `width style color`. We can get style borders the way we want with Atomizer by using those 3 but a common use case is to style border with  a single pixel, so what we added to the helper classes are border declarations mixing both `style` and `width`

> that way authors can do this: `Bd Bdc-000` to get a black border around a box instead of having to go verbose with Atomic `Bdc-000 Bds-s Bdw-1px`

**Comment by 3den** [comment]
It would be nice to allow this helpers to be expecified on the configs or to allow 3rd party to create node_modules that extend atomizer, we should make easy for people to create their own helpers.

**Comment by src-code** [comment]
@3den: Yes, that's the plan!  You will be able to add new rulesets for whatever custom helpers, etc you might want.

**Comment by thierryk** [comment]
Let's make sure we allow namespacing of those too; but with an *arbitrary string*, **not** necessarily the same as the one used for "Atomic classes".

**Comment by renatoi** [comment]
All helpers have been added to 3.0.0-alpha.4. Custom rulesets have been supported for a while as well (not sure since when).
